Parameters:
    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
        Type: AWS::EC2::KeyPair::KeyName # Resource identifier
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
    InstanceType:
        Description: WebServer EC2 instance type (has default, AllowedValues)
        Type: String
        Default: t2.micro
        AllowedValues: #possible values LIST
            - t1.micro
            - t2.nano
            - t2.micro
            - t2.small
            - t3.micro
    SSHLocation:
        Description: The IP address range that can be used to communicate to the EC2 instances
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0 
        AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
        ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    #CodeCommit Parameter:
  
    ImageID:
        Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
        Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    

Resources:
    Webserver:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref ImageID
            InstanceType: !Ref InstanceType # Reference to the instance type param
            KeyName: !Ref KeyName
            SecurityGroupIds:
                - !Ref WebserverSecurityGroup
            Tags:
                 - Key: Name
                   Value: Ec2-UserData-Template

            UserData:
                Fn::Base64: |
                    #!/bin/bash -xe
                    yum update -y 
                    yum install httpd -y
                    systemctl start httpd
                    systemctl enable httpd
                    echo "Building a 3 stages CodePipeline including Source Stage or CodeCommit-CodeBuild-CodeDeploy" > var/www/html/index.html

    WebserverSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: Enable HTTP access via port 80 + SSH
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  FromPort: '80'
                  IpProtocol: tcp
                  ToPort: '80'
                - CidrIp: !Ref SSHLocation
                  FromPort: '22'
                  IpProtocol: tcp
                  ToPort: '22'
            
Outputs:
    InstanceID:
        Description: InstanceID of the newly created EC2 Instance
        Value: !GetAtt Webserver.PublicIp